/**
 * QwQnanoclaw Agent Runner
 * Runs inside a container, receives config via stdin, outputs result to stdout
 *
 * Input protocol:
 *   Stdin: Full ContainerInput JSON (read until EOF, like before)
 *   IPC:   Follow-up messages written as JSON files to /workspace/ipc/input/
 *          Files: {type:"message", text:"..."}.json — polled and consumed
 *          Sentinel: /workspace/ipc/input/_close — signals session end
 *
 * Stdout protocol:
 *   Each result is wrapped in OUTPUT_START_MARKER / OUTPUT_END_MARKER pairs.
 *   Multiple results may be emitted (one per agent teams result).
 *   Final marker after loop ends signals completion.
 */

import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { fileURLToPath } from 'url';

interface ContainerInput {
  prompt: string;
  sessionId?: string;
  groupFolder: string;
  chatJid: string;
  isMain: boolean;
  isScheduledTask?: boolean;
  assistantName?: string;
}

interface ContainerOutput {
  status: 'success' | 'error';
  result: string | null;
  newSessionId?: string;
  error?: string;
}

interface SessionEntry {
  sessionId: string;
  fullPath: string;
  summary: string;
  firstPrompt: string;
}

interface SessionsIndex {
  entries: SessionEntry[];
}

const OUTPUT_START_MARKER = '---QWQNANOCLAW_OUTPUT_START---';
const OUTPUT_END_MARKER = '---QWQNANOCLAW_OUTPUT_END---';

const GROUPS_DIR = '/workspace/project/groups';
const DATA_DIR = '/workspace/project/.data';
const IPC_INPUT_DIR = '/workspace/ipc/input';
const IPC_OUTPUT_DIR = '/workspace/ipc/output';
const IPC_POLL_MS = 500;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const mcpServerPath = path.join(__dirname, 'ipc-mcp-stdio.ts');

function log(message: string): void {
  console.error(`[AgentRunner] ${message}`);
}

function writeOutput(data: string): void {
  console.log(`${OUTPUT_START_MARKER}${data}${OUTPUT_END_MARKER}`);
}

function writeError(error: string): void {
  writeOutput(JSON.stringify({ status: 'error', error }));
}

function sanitizeFilename(summary: string): string {
  return summary
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50);
}

function generateFallbackName(): string {
  const time = new Date();
  return `conversation-${time.getHours().toString().padStart(2, '0')}${time.getMinutes().toString().padStart(2, '0')}`;
}

function parseTranscript(content: string): { role: 'user' | 'assistant'; content: string }[] {
  const messages: { role: 'user' | 'assistant'; content: string }[] = [];
  for (const line of content.split('\n')) {
    if (!line.trim()) continue;
    try {
      const entry = JSON.parse(line);
      if (entry.type === 'user' && entry.message?.content) {
        const text = typeof entry.message.content === 'string'
          ? entry.message.content
          : JSON.stringify(entry.message.content);
        messages.push({ role: 'user', content: text });
      } else if (entry.type === 'assistant' && entry.message?.content) {
        const text = typeof entry.message.content === 'string'
          ? entry.message.content
          : JSON.stringify(entry.message.content);
        messages.push({ role: 'assistant', content: text });
      }
    } catch {
      continue;
    }
  }
  return messages;
}

function formatTranscriptMarkdown(messages: { role: 'user' | 'assistant'; content: string }[], summary: string, assistantName?: string): string {
  const lines: string[] = [];
  lines.push(`# Conversation Summary: ${summary}`);
  lines.push(`Generated by ${assistantName || 'QwQnanoclaw'}`);
  lines.push('');
  for (const msg of messages) {
    lines.push(`## ${msg.role.toUpperCase()}`);
    lines.push(msg.content);
    lines.push('');
  }
  return lines.join('\n');
}

function getSessionSummary(sessionId: string | undefined, transcriptPath: string): string | null {
  try {
    const content = fs.readFileSync(transcriptPath, 'utf-8');
    const messages = parseTranscript(content);
    if (messages.length === 0) return null;
    const firstUser = messages.find(m => m.role === 'user');
    return firstUser ? sanitizeFilename(firstUser.content) : null;
  } catch {
    return null;
  }
}

function drainIpcInput(): string[] {
  try {
    fs.mkdirSync(IPC_INPUT_DIR, { recursive: true });
    const files = fs.readdirSync(IPC_INPUT_DIR)
      .filter(f => f.endsWith('.json'))
      .sort();

    const messages: string[] = [];
    for (const file of files) {
      const filePath = path.join(IPC_INPUT_DIR, file);
      try {
        const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
        fs.unlinkSync(filePath);
        if (data.type === 'message' && data.text) {
          messages.push(data.text);
        }
      } catch (err) {
        log(`Failed to process input file ${file}: ${err instanceof Error ? err.message : String(err)}`);
        try { fs.unlinkSync(filePath); } catch { /* ignore */ }
      }
    }
    return messages;
  } catch (err) {
    log(`IPC drain error: ${err instanceof Error ? err.message : String(err)}`);
    return [];
  }
}

function waitForIpcMessage(): Promise<string | null> {
  return new Promise((resolve) => {
    const poll = () => {
      if (shouldClose()) {
        resolve(null);
        return;
      }
      const messages = drainIpcInput();
      if (messages.length > 0) {
        resolve(messages.join('\n'));
        return;
      }
      setTimeout(poll, IPC_POLL_MS);
    };
    poll();
  });
}

async function runQuery(
  prompt: string,
  sessionId: string | undefined,
  mcpServerPath: string,
  containerInput: ContainerInput,
  sdkEnv: Record<string, string | undefined>,
  resumeAt?: string,
): Promise<{ newSessionId?: string; lastAssistantUuid?: string; closedDuringQuery: boolean }> {
  const globalQwenMdPath = '/workspace/global/QWEN.md';
  let globalQwenMd: string | undefined;
  if (!containerInput.isMain && fs.existsSync(globalQwenMdPath)) {
    globalQwenMd = fs.readFileSync(globalQwenMdPath, 'utf-8');
  }

  // Create settings.json in /workspace/group/.qwen/ to configure Qwen Code
  const groupQwenDir = '/workspace/group/.qwen';
  if (!fs.existsSync(groupQwenDir)) {
    fs.mkdirSync(groupQwenDir, { recursive: true });
  }
  const settingsFile = path.join(groupQwenDir, 'settings.json');
  
  // Write QWEN.md to group directory only if it doesn't exist
  // This preserves user-customized names (e.g., "小猫", "小狗") in existing sessions
  const qwenMdPath = '/workspace/group/QWEN.md';
  if (globalQwenMd && !fs.existsSync(qwenMdPath)) {
    fs.writeFileSync(qwenMdPath, globalQwenMd);
    log(`Wrote QWEN.md to ${qwenMdPath} (first time)`);
  }
  
  // Write SYSTEM.md to group directory only if it doesn't exist
  // This overrides the default "You are Qwen Code" system prompt
  const systemMdPath = '/workspace/group/SYSTEM.md';
  if (globalQwenMd && !fs.existsSync(systemMdPath)) {
    const globalSystemMdPath = '/workspace/global/SYSTEM.md';
    if (fs.existsSync(globalSystemMdPath)) {
      const globalSystemMd = fs.readFileSync(globalSystemMdPath, 'utf-8');
      fs.writeFileSync(systemMdPath, globalSystemMd);
      log(`Wrote SYSTEM.md to ${systemMdPath} (first time)`);
    }
  }
  
  if (!fs.existsSync(settingsFile)) {
    fs.writeFileSync(settingsFile, JSON.stringify({
      env: {
        // Enable agent swarms (subagent orchestration)
        QWEN_CODE_EXPERIMENTAL_AGENT_TEAMS: '1',
        // Enable Qwen Code's memory feature
        QWEN_CODE_DISABLE_AUTO_MEMORY: '0',
      },
      $version: 3,
    }, null, 2) + '\n');
    log(`Created settings.json at ${settingsFile}`);
  }

  const extraDirs: string[] = [];
  const extraBase = '/workspace/extra';
  if (fs.existsSync(extraBase)) {
    for (const entry of fs.readdirSync(extraBase)) {
      const fullPath = path.join(extraBase, entry);
      if (fs.statSync(fullPath).isDirectory()) {
        extraDirs.push(fullPath);
      }
    }
  }
  if (extraDirs.length > 0) {
    log(`Additional directories: ${extraDirs.join(', ')}`);
  }

  // Use Qwen CLI dynamically - find global installation path
  const possiblePaths = [
    // npm global path (Windows)
    path.join(process.env.APPDATA || '', 'npm/node_modules/@qwen-code/qwen-code/cli.js'),
    // yarn global path (Windows)
    path.join(process.env.APPDATA || '', 'yarn/global/node_modules/@qwen-code/qwen-code/cli.js'),
    // pnpm global path (Windows)
    path.join(process.env.APPDATA || '', 'pnpm/global/node_modules/@qwen-code/qwen-code/cli.js'),
  ];
  
  let qwenPath = possiblePaths.find(p => fs.existsSync(p));
  
  // If not found, try to get from npm prefix
  if (!qwenPath) {
    try {
      const { execSync } = require('child_process');
      const npmPrefix = execSync('npm prefix -g', { encoding: 'utf-8' }).trim();
      const prefixedPath = path.join(npmPrefix, 'node_modules/@qwen-code/qwen-code/cli.js');
      if (fs.existsSync(prefixedPath)) {
        qwenPath = prefixedPath;
      }
    } catch (e) {
      // Ignore error, will use fallback
    }
  }
  
  // Fallback to 'qwen' command in PATH
  if (!qwenPath) {
    qwenPath = 'qwen';
  }
  
  const args = ['--prompt', prompt];

  if (sessionId) {
    args.push('--sessionId', sessionId);
  }

  if (resumeAt) {
    args.push('--resumeAt', resumeAt);
  }

  return new Promise((resolve, reject) => {
    const child = spawn('node', [qwenPath, ...args], {
      cwd: '/workspace/group',
      env: {
        ...process.env,
        ...sdkEnv,
        DASHSCOPE_API_KEY: process.env.DASHSCOPE_API_KEY || '',
        // Set QWEN_SYSTEM_MD to override default system prompt (replaces "You are Qwen Code" with "You are Andy")
        QWEN_SYSTEM_MD: '/workspace/group/SYSTEM.md',
      },
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let output = '';
    let errorOutput = '';

    child.stdout.on('data', (data) => {
      output += data.toString();
      writeOutput(data.toString());
    });

    child.stderr.on('data', (data) => {
      errorOutput += data.toString();
      log(`Qwen CLI stderr: ${data.toString()}`);
    });

    child.on('close', (code) => {
      if (code === 0) {
        resolve({ newSessionId: sessionId, lastAssistantUuid: undefined, closedDuringQuery: false });
      } else {
        reject(new Error(`Qwen CLI exited with code ${code}: ${errorOutput}`));
      }
    });

    child.on('error', (err) => {
      reject(err);
    });
  });
}

function shouldClose(): boolean {
  return fs.existsSync(path.join(IPC_INPUT_DIR, '_close'));
}

async function main(): Promise<void> {
  log('Agent runner starting...');

  const stdinData = await new Promise<string>((resolve) => {
    let data = '';
    process.stdin.on('data', chunk => { data += chunk; });
    process.stdin.on('end', () => resolve(data));
  });

  let containerInput: ContainerInput;
  try {
    containerInput = JSON.parse(stdinData);
  } catch (err) {
    writeError(`Failed to parse stdin JSON: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  }

  log(`Processing prompt for group ${containerInput.groupFolder}`);

  const groupDir = path.join(GROUPS_DIR, containerInput.groupFolder);
  const sessionsDir = path.join(DATA_DIR, 'sessions', containerInput.groupFolder);
  const sessionsIndexFile = path.join(sessionsDir, 'index.json');

  fs.mkdirSync(sessionsDir, { recursive: true });

  // Qwen Code reads API Key from ~/.qwen/settings.json automatically
  // No need to pass secrets from container-runner
  const sdkEnv: Record<string, string | undefined> = {};

  let sessionId = containerInput.sessionId;
  let resumeAt: string | undefined;

  if (sessionId) {
    try {
      const index: SessionsIndex = JSON.parse(fs.readFileSync(sessionsIndexFile, 'utf-8'));
      const entry = index.entries.find(e => e.sessionId === sessionId);
      if (entry) {
        resumeAt = entry.fullPath;
      } else {
        // Session ID not found in index, clear it to create a new session
        log(`Session ${sessionId} not found in index, will create new session`);
        sessionId = undefined;
      }
    } catch (err) {
      log(`Failed to load session index: ${err instanceof Error ? err.message : String(err)}`);
      // If index file is corrupted or missing, clear sessionId to create new session
      sessionId = undefined;
    }
  }

  try {
    const result = await runQuery(
      containerInput.prompt,
      sessionId,
      mcpServerPath,
      containerInput,
      sdkEnv,
      resumeAt,
    );

    if (result.newSessionId && !sessionId) {
      sessionId = result.newSessionId;
      const entry: SessionEntry = {
        sessionId,
        fullPath: path.join(sessionsDir, `${sessionId}.jsonl`),
        summary: containerInput.prompt.slice(0, 50),
        firstPrompt: containerInput.prompt,
      };
      const index: SessionsIndex = { entries: [entry] };
      fs.writeFileSync(sessionsIndexFile, JSON.stringify(index, null, 2));
    }

    writeOutput(JSON.stringify({ status: 'success', result: 'Query completed' }));
  } catch (err) {
    writeError(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }

  log('Agent runner finished');
}

main().catch(err => {
  writeError(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
